### PR TITLE
Add support for setting highlighted days

### PR DESCRIPTION
**Pull request by domyn**
This pull request adds simple support for setting list of days which are to be displayed in different color, for example holidays, as requested in #118.

### CODE REVIEW

**Comment by domyn** [comment]
As Github does not allow changing source branch in pull request, I've recreated it as #184.

**Comment by mateuszSawa** [comment]
@domyn You are breaking our licenses by creating: pl.domyno:material-calendar-view:1.5.2 !

**Comment by domyn** [comment]
As the project is licensed under the Apache License 2.0, it has given me right to modify and redistribute it, preserving original license information.

**Comment by mateuszSawa** [comment]
@domyn sure but in previous version you didn't add license information

**Comment by domyn** [comment]
Okay, I was sure that I added license information, will fix that.

**Pull request closed without merging**
