### PR TITLE
build plugin version + libs version update

### PR DESCRIPTION
**Pull request by mitrejcevski**

### CODE REVIEW

**Comment by mitrejcevski** [comment]
@kormateusz may you tell few words why this is not getting in? I started using the lib and I was thinking of contributing more further on too...

**Comment by kormateusz** [comment]
Hi, currently we don't want to update libraries because some new versions of them causes problems when users has older versions in them projects.

**Comment by mitrejcevski** [comment]
Oh, I see. Thanks for info. I thought PR's are not welcome at all :)

**Comment by kormateusz** [comment]
No, just don't update libraries, please :)

**Pull request closed without merging**
